"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-(t^)5m_fk!i!rcsg_9pvxx=*zx75-mar31*ruf+lpq-9d68i)f"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'corsheaders',
    'rest_framework',
    "salesoptimizer"
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'salesoptimizer.pagination.StandardPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "salesoptimizer",
        "USER": "root",
        "PASSWORD": "Amir@13511348",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/stable/howto/static-files/

STATIC_URL = '/static/'

# Directory where Django will look for static files during development
STATICFILES_DIRS = [
    BASE_DIR / "static",
    # os.path.join(BASE_DIR, 'static'),  # Alternative using os
]

# Directory where collectstatic will gather all static files (for production)
STATIC_ROOT = BASE_DIR / "staticfiles"
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Alternative using os


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}

# settings.py - Add at the very end of the file

import sys
import django.template.context

# Monkey patch for Python 3.14 compatibility
if sys.version_info >= (3, 14):
    # Save original methods
    original_copy = django.template.context.Context.__copy__
    
    def patched_copy(self):
        """Patched __copy__ method for Python 3.14 compatibility"""
        try:
            # Try the original copy method
            return original_copy(self)
        except AttributeError:
            # Fallback for Python 3.14
            # Create a new context manually
            from django.template.context import Context
            new_context = Context()
            # Copy all attributes manually
            if hasattr(self, 'dicts'):
                new_context.dicts = self.dicts[:]
            else:
                # For Python 3.14, iterate through items
                for key, value in self.items():
                    new_context[key] = value
            # Copy other important attributes
            if hasattr(self, 'autoescape'):
                new_context.autoescape = self.autoescape
            if hasattr(self, 'use_l10n'):
                new_context.use_l10n = self.use_l10n
            if hasattr(self, 'use_tz'):
                new_context.use_tz = self.use_tz
            if hasattr(self, 'template_name'):
                new_context.template_name = self.template_name
            if hasattr(self, 'render_context'):
                new_context.render_context = self.render_context
            return new_context
    
    # Replace the __copy__ method
    django.template.context.Context.__copy__ = patched_copy
    
    # Also patch the new method if it exists
    if hasattr(django.template.context.Context, 'new'):
        original_new = django.template.context.Context.new
        
        def patched_new(self, values=None):
            """Patched new method for Python 3.14 compatibility"""
            try:
                return original_new(self, values)
            except AttributeError:
                from django.template.context import Context
                new_context = Context(values)
                if hasattr(self, 'autoescape'):
                    new_context.autoescape = self.autoescape
                if hasattr(self, 'use_l10n'):
                    new_context.use_l10n = self.use_l10n
                if hasattr(self, 'use_tz'):
                    new_context.use_tz = self.use_tz
                if hasattr(self, 'template_name'):
                    new_context.template_name = self.template_name
                if hasattr(self, 'render_context'):
                    new_context.render_context = self.render_context
                return new_context
        
        django.template.context.Context.new = patched_new
    