# Generated by Django 5.0.9 on 2026-08-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        db_column="product_id",
                        help_text="Unique product code/SKU",
                        max_length=50,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        db_column="product_name",
                        help_text="Product name",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "first_receipt_date",
                    models.DateField(
                        blank=True,
                        db_column="first_receipt_date",
                        help_text="Date of first inventory receipt",
                        null=True,
                    ),
                ),
                (
                    "total_inventory",
                    models.DecimalField(
                        blank=True,
                        db_column="total_inventory",
                        decimal_places=6,
                        help_text="Total inventory received (sum of all vouchers)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "sales_percentage",
                    models.DecimalField(
                        blank=True,
                        db_column="sales_percentage",
                        decimal_places=2,
                        help_text="Percentage of inventory sold",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "days_since_first_receipt",
                    models.IntegerField(
                        blank=True,
                        db_column="days_since_first_receipt",
                        help_text="Days since first receipt at analysis date",
                        null=True,
                    ),
                ),
                (
                    "days_since_last_sale",
                    models.IntegerField(
                        blank=True,
                        db_column="days_since_last_sale",
                        help_text="Days since last sale at analysis date",
                        null=True,
                    ),
                ),
                (
                    "stock_status",
                    models.CharField(
                        blank=True,
                        db_column="stock_status",
                        help_text="Stock status: Complete or Incomplete",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "dead_stock_tag",
                    models.CharField(
                        blank=True,
                        db_column="dead_stock_tag",
                        help_text="Dead stock classification tag",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "priority_rank",
                    models.IntegerField(
                        blank=True,
                        db_column="priority_rank",
                        help_text="Priority rank (1 = most urgent)",
                        null=True,
                    ),
                ),
                (
                    "recommended_action",
                    models.CharField(
                        blank=True,
                        db_column="recommended_action",
                        help_text="Recommended action for the product",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "expected_milestone",
                    models.IntegerField(
                        blank=True,
                        db_column="expected_milestone",
                        help_text="Expected milestone percentage based on age",
                        null=True,
                    ),
                ),
                (
                    "days_to_10",
                    models.IntegerField(
                        blank=True,
                        db_column="days_to_10",
                        help_text="Days to reach 10% sales",
                        null=True,
                    ),
                ),
                (
                    "days_to_20",
                    models.IntegerField(
                        blank=True,
                        db_column="days_to_20",
                        help_text="Days to reach 20% sales",
                        null=True,
                    ),
                ),
                (
                    "days_to_30",
                    models.IntegerField(
                        blank=True,
                        db_column="days_to_30",
                        help_text="Days to reach 30% sales",
                        null=True,
                    ),
                ),
                (
                    "days_to_40",
                    models.IntegerField(
                        blank=True,
                        db_column="days_to_40",
                        help_text="Days to reach 40% sales",
                        null=True,
                    ),
                ),
                (
                    "days_to_50",
                    models.IntegerField(
                        blank=True,
                        db_column="days_to_50",
                        help_text="Days to reach 50% sales",
                        null=True,
                    ),
                ),
                (
                    "days_to_60",
                    models.IntegerField(
                        blank=True,
                        db_column="days_to_60",
                        help_text="Days to reach 60% sales",
                        null=True,
                    ),
                ),
                (
                    "days_to_70",
                    models.IntegerField(
                        blank=True,
                        db_column="days_to_70",
                        help_text="Days to reach 70% sales",
                        null=True,
                    ),
                ),
                (
                    "days_to_80",
                    models.IntegerField(
                        blank=True,
                        db_column="days_to_80",
                        help_text="Days to reach 80% sales",
                        null=True,
                    ),
                ),
                (
                    "days_to_90",
                    models.IntegerField(
                        blank=True,
                        db_column="days_to_90",
                        help_text="Days to reach 90% sales",
                        null=True,
                    ),
                ),
                (
                    "days_to_100",
                    models.IntegerField(
                        blank=True,
                        db_column="days_to_100",
                        help_text="Days to reach 100% sales",
                        null=True,
                    ),
                ),
                (
                    "threshold_10_date",
                    models.DateField(
                        blank=True,
                        db_column="threshold_10_date",
                        help_text="Date when 10% sales was reached",
                        null=True,
                    ),
                ),
                (
                    "threshold_20_date",
                    models.DateField(
                        blank=True,
                        db_column="threshold_20_date",
                        help_text="Date when 20% sales was reached",
                        null=True,
                    ),
                ),
                (
                    "threshold_30_date",
                    models.DateField(
                        blank=True,
                        db_column="threshold_30_date",
                        help_text="Date when 30% sales was reached",
                        null=True,
                    ),
                ),
                (
                    "threshold_40_date",
                    models.DateField(
                        blank=True,
                        db_column="threshold_40_date",
                        help_text="Date when 40% sales was reached",
                        null=True,
                    ),
                ),
                (
                    "threshold_50_date",
                    models.DateField(
                        blank=True,
                        db_column="threshold_50_date",
                        help_text="Date when 50% sales was reached",
                        null=True,
                    ),
                ),
                (
                    "threshold_60_date",
                    models.DateField(
                        blank=True,
                        db_column="threshold_60_date",
                        help_text="Date when 60% sales was reached",
                        null=True,
                    ),
                ),
                (
                    "threshold_70_date",
                    models.DateField(
                        blank=True,
                        db_column="threshold_70_date",
                        help_text="Date when 70% sales was reached",
                        null=True,
                    ),
                ),
                (
                    "threshold_80_date",
                    models.DateField(
                        blank=True,
                        db_column="threshold_80_date",
                        help_text="Date when 80% sales was reached",
                        null=True,
                    ),
                ),
                (
                    "threshold_90_date",
                    models.DateField(
                        blank=True,
                        db_column="threshold_90_date",
                        help_text="Date when 90% sales was reached",
                        null=True,
                    ),
                ),
                (
                    "threshold_100_date",
                    models.DateField(
                        blank=True,
                        db_column="threshold_100_date",
                        help_text="Date when 100% sales was reached",
                        null=True,
                    ),
                ),
                (
                    "cat_avg_days_to_10",
                    models.DecimalField(
                        blank=True,
                        db_column="cat_avg_days_to_10",
                        decimal_places=2,
                        help_text="Category average days to reach 10%",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "cat_avg_days_to_20",
                    models.DecimalField(
                        blank=True,
                        db_column="cat_avg_days_to_20",
                        decimal_places=2,
                        help_text="Category average days to reach 20%",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "cat_avg_days_to_30",
                    models.DecimalField(
                        blank=True,
                        db_column="cat_avg_days_to_30",
                        decimal_places=2,
                        help_text="Category average days to reach 30%",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "cat_avg_days_to_40",
                    models.DecimalField(
                        blank=True,
                        db_column="cat_avg_days_to_40",
                        decimal_places=2,
                        help_text="Category average days to reach 40%",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "cat_avg_days_to_50",
                    models.DecimalField(
                        blank=True,
                        db_column="cat_avg_days_to_50",
                        decimal_places=2,
                        help_text="Category average days to reach 50%",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "cat_avg_days_to_60",
                    models.DecimalField(
                        blank=True,
                        db_column="cat_avg_days_to_60",
                        decimal_places=2,
                        help_text="Category average days to reach 60%",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "cat_avg_days_to_70",
                    models.DecimalField(
                        blank=True,
                        db_column="cat_avg_days_to_70",
                        decimal_places=2,
                        help_text="Category average days to reach 70%",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "cat_avg_days_to_80",
                    models.DecimalField(
                        blank=True,
                        db_column="cat_avg_days_to_80",
                        decimal_places=2,
                        help_text="Category average days to reach 80%",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "cat_avg_days_to_90",
                    models.DecimalField(
                        blank=True,
                        db_column="cat_avg_days_to_90",
                        decimal_places=2,
                        help_text="Category average days to reach 90%",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "cat_avg_days_to_100",
                    models.DecimalField(
                        blank=True,
                        db_column="cat_avg_days_to_100",
                        decimal_places=2,
                        help_text="Category average days to reach 100%",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "analysis_date",
                    models.DateField(
                        blank=True,
                        db_column="analysis_date",
                        help_text="Date when analysis was performed",
                        null=True,
                    ),
                ),
                (
                    "products_from_date",
                    models.DateField(
                        blank=True,
                        db_column="products_from_date",
                        help_text="Start date for products included in analysis",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="created_at",
                        help_text="Timestamp when record was created",
                    ),
                ),
            ],
            options={
                "db_table": "productcycle",
                "ordering": ["priority_rank", "product_id"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductCycleAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_id",
                    models.IntegerField(
                        blank=True,
                        db_column="category_id",
                        help_text="Category ID",
                        null=True,
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        blank=True,
                        db_column="category_name",
                        help_text="Category name",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "dead_stock_tag",
                    models.CharField(
                        blank=True,
                        db_column="dead_stock_tag",
                        help_text="Dead stock classification tag",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "product_count",
                    models.IntegerField(
                        blank=True,
                        db_column="product_count",
                        help_text="Number of products in this category/tag",
                        null=True,
                    ),
                ),
                (
                    "avg_sales_percentage",
                    models.DecimalField(
                        blank=True,
                        db_column="avg_sales_percentage",
                        decimal_places=2,
                        help_text="Average sales percentage",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "avg_age_days",
                    models.IntegerField(
                        blank=True,
                        db_column="avg_age_days",
                        help_text="Average age in days",
                        null=True,
                    ),
                ),
                (
                    "total_inventory_units",
                    models.DecimalField(
                        blank=True,
                        db_column="total_inventory_units",
                        decimal_places=2,
                        help_text="Total inventory units",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "min_priority_rank",
                    models.IntegerField(
                        blank=True,
                        db_column="min_priority_rank",
                        help_text="Minimum priority rank in this group",
                        null=True,
                    ),
                ),
                (
                    "analysis_date",
                    models.DateField(
                        blank=True,
                        db_column="analysis_date",
                        help_text="Date when analysis was performed",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="created_at",
                        help_text="Timestamp when record was created",
                    ),
                ),
            ],
            options={
                "db_table": "productcycle_aggregation",
                "ordering": ["category_id", "min_priority_rank", "dead_stock_tag"],
                "managed": False,
            },
        ),
    ]
